name: ugpcl_unet_r50

include:
  - ../_models/unet_tf_r50.yaml
  - ../_trainers/ugpcl.yaml

dataset:
  name: isic
  kwargs:
    # root_dir: /opt/data/private/zyb/dataset/msnet/TrainDataset
    #root_dir: /opt/data/private/zyb/dataset/ISIC2018/TrainDataset
    root_dir: /opt/data/private/wd/Dataset/Kvasir/TrainDataset
    # root_dir: /opt/data/private/wd/Dataset/Kvasir/TestDataset/Kvasir
    channels: 3
    labeled_bs: 8
    batch_size: 16
    batch_size_val: 16
    num_workers: 1
    labeled_ratio: 0.125
    train_transforms:
      - name: Resize
        kwargs: { size: [ 224, 224 ] }
      - name: ToTensor
      - name: RandomCrop
        kwargs: { size: [ 224, 224 ] }
      - name: RandomFlip
        kwargs: { p: 0.5 }
      - name: ColorJitter
        kwargs: { brightness: 0.4,contrast: 0.4,saturation: 0.4, hue: 0.1, p: 0.8 }
      - name: Normalize
        kwargs: { mean: [ 0.485, 0.456, 0.406 ], std: [ 0.229, 0.224, 0.225 ] }
    val_transforms:
      - name: Resize
        kwargs: { size: [ 224, 224 ] }
      - name: ToTensor
      - name: Normalize
        kwargs: { mean: [ 0.485, 0.456, 0.406 ], std: [ 0.229, 0.224, 0.225 ] }

train:
  name: UGPCLTrainer
  kwargs:
    criterions:
      - name: DiceLoss_
        kwargs: { weight: 0.5, n_classes: 2, class_weight: [ 0.0, 1.0 ] }
      - name: CrossEntropyLoss_
        kwargs: { weight: 0.5 }
    metrics:
      - name: Dice
        kwargs:
          name: Dice
          class_indexs: [ 0, 1 ]
          class_names: [ bg, c ]
      - name: Jaccard
        kwargs:
          name: Jaccard
          class_indexs: [ 0, 1 ]
          class_names: [ bg, c ]
    labeled_bs: 8
    consistency: 0.0
    consistency_rampup: 40.0
    max_iter: 6000
    eval_interval: 500
    save_image_interval: 50
    save_ckpt_interval: 1000


model:
  name: UNetTF
  kwargs:
    in_channels: 3
    classes: 2
    contrast_embed: True
    contrast_embed_index: -3

scheduler:
  name: PolyLR
  kwargs:
    max_iters: 6000
    power: 0.9
    last_epoch: -1
    min_lr: 0.0001