dataset:
  name: isic  # 数据集名称为colon
  kwargs:
    root_dir: /opt/data/private/wd/Dataset/Kvasir/TrainDataset
    # root_dir: /opt/data/private/zyb/dataset/ISIC2018/TrainDataset
    channels: 3
    labeled_bs: 8
    batch_size: 16
    batch_size_val: 16
    num_workers: 1
    labeled_ratio: 0.25

    train_transforms:
      - name: Resize
        kwargs: { size: [ 224, 224 ] }
      - name: ToTensor
      - name: RandomCrop
        kwargs: { size: [ 224, 224 ] }
      - name: RandomFlip
        kwargs: { p: 0.5 }
      - name: ColorJitter
        kwargs: { brightness: 0.4,contrast: 0.4,saturation: 0.4, hue: 0.1, p: 0.8 }
      - name: Normalize
        kwargs: { mean: [ 0.485, 0.456, 0.406 ], std: [ 0.229, 0.224, 0.225 ] }
    val_transforms:
      - name: Resize
        kwargs: { size: [ 224, 224 ] }
      - name: ToTensor
      - name: Normalize
        kwargs: { mean: [ 0.485, 0.456, 0.406 ], std: [ 0.229, 0.224, 0.225 ] }


